on:
  schedule:
    - cron: '0 9,15 * * 1-5'

jobs:
  deploy:
    name: Review reminders
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: blombard/review-reminder@master
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        reminder-comment: "Don't forget to review this PR !"
        days-before-reminder: '1'