name: read-yaml

on:
  workflow_call:
    inputs:
      file_name:
        required: true
        type: string

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    outputs:
      location: ${{ steps.read_yaml.outputs.location }}
      namespace: ${{ steps.read_yaml.outputs.namespace }}
      postfix: ${{ steps.read_yaml.outputs.postfix }}
      environment: ${{ steps.read_yaml.outputs.environment }}
      resource_count: ${{ steps.read_yaml.outputs.resource_count }}
      location_abbreviation: ${{ steps.read_yaml.outputs.location_abbreviation }}
      enable_aml_computecluster: ${{ steps.read_yaml.outputs.enable_aml_computecluster }}
      enable_monitoring: ${{ steps.read_yaml.outputs.enable_monitoring }}
      resource_group: ${{ steps.read_yaml.outputs.resource_group }}
      aml_workspace: ${{ steps.read_yaml.outputs.aml_workspace }}
      bep: ${{ steps.read_yaml.outputs.bep }}
      oep: ${{ steps.read_yaml.outputs.oep }}
      terraform_version: ${{ steps.read_yaml.outputs.terraform_version }}
      terraform_workingdir: ${{ steps.read_yaml.outputs.terraform_workingdir }}
      terraform_st_location: ${{ steps.read_yaml.outputs.terraform_st_location }}
      terraform_st_resource_group: ${{ steps.read_yaml.outputs.terraform_st_resource_group }}
      terraform_st_storage_account: ${{ steps.read_yaml.outputs.terraform_st_storage_account }}
      terraform_st_container_name: ${{ steps.read_yaml.outputs.terraform_st_container_name }}
      terraform_st_key: ${{ steps.read_yaml.outputs.terraform_st_key }}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Read YAML file
        id: read_yaml
        run: |
          echo "location=${{ steps.read_yaml.outputs.contents.location }}" >> $GITHUB_OUTPUT
          echo "namespace=${{ steps.read_yaml.outputs.contents.namespace }}" >> $GITHUB_OUTPUT
          echo "postfix=${{ steps.read_yaml.outputs.contents.postfix }}" >> $GITHUB_OUTPUT
          echo "environment=${{ steps.read_yaml.outputs.contents.environment }}" >> $GITHUB_OUTPUT
          echo "resource_count=${{ steps.read_yaml.outputs.contents.resource_count }}" >> $GITHUB_OUTPUT
          echo "location_abbreviation=${{ steps.read_yaml.outputs.contents.location_abbreviation }}" >> $GITHUB_OUTPUT
          echo "enable_aml_computecluster=${{ steps.read_yaml.outputs.contents.enable_aml_computecluster }}" >> $GITHUB_OUTPUT
          echo "enable_monitoring=${{ steps.read_yaml.outputs.contents.enable_monitoring }}" >> $GITHUB_OUTPUT
          echo "resource_group=${{ steps.read_yaml.outputs.contents.resource_group }}" >> $GITHUB_OUTPUT
          echo "aml_workspace=${{ steps.read_yaml.outputs.contents.aml_workspace }}" >> $GITHUB_OUTPUT
          echo "bep=${{ steps.read_yaml.outputs.contents.bep }}" >> $GITHUB_OUTPUT
          echo "oep=${{ steps.read_yaml.outputs.contents.oep }}" >> $GITHUB_OUTPUT
          echo "terraform_version=${{ steps.read_yaml.outputs.contents.terraform_version }}" >> $GITHUB_OUTPUT
          echo "terraform_workingdir=${{ steps.read_yaml.outputs.contents.terraform_workingdir }}" >> $GITHUB_OUTPUT
          echo "terraform_st_location=${{ steps.read_yaml.outputs.contents.terraform_st_location }}" >> $GITHUB_OUTPUT
          echo "terraform_st_resource_group=${{ steps.read_yaml.outputs.contents.terraform_st_resource_group }}" >> $GITHUB_OUTPUT
          echo "terraform_st_storage_account=${{ steps.read_yaml.outputs.contents.terraform_st_storage_account }}" >> $GITHUB_OUTPUT
          echo "terraform_st_container_name=${{ steps.read_yaml.outputs.contents.terraform_st_container_name }}" >> $GITHUB_OUTPUT
          echo "terraform_st_key=${{ steps.read_yaml.outputs.contents.terraform_st_key }}" >> $GITHUB_OUTPUT
