name: register-environment

on:
  workflow_call:
    inputs:
      dply_environment:
        type: string
        required: true 
      environment_file:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      workspace_name:
        required: true
        type: string
      conda_file:
        required: false
        default: ""
        type: string
      dockerfile-location:
        required: false
        default: ""
        type: string
    secrets:
      creds:
        required: true
jobs:
  register-environment:
    runs-on: self-hosted
    environment: ${{ inputs.dply_environment }}
    steps:
      - name: Get Public IP Address
        id: get_ip
        run: echo "::set-output name=ip_address::$(curl -s ifconfig.me)"
      - name: Display IP Address
        run: echo "Public IP Address is ${{ steps.get_ip.outputs.ip_address }}"
      - name: checkout
        uses: actions/checkout@v3
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true
      - name: install-extension
        run: az extension add -n ml -y
      - name: update-extension
        run: az extension update -n ml
      - name: list-extentions
        run: az extension list
      - name: create-environment-from-file-with-conda
        if: ${{ inputs.conda_file != ''}}
        run: |
          az ml environment create --file ${{ github.workspace }}/${{ inputs.environment_file }} --resource-group ${{ inputs.resource_group }} \
                                --workspace-name ${{ inputs.workspace_name }} --conda-file ${{ github.workspace }}/${{ inputs.conda_file }}
      - name: create-environment-from-file-without-conda
        if: ${{ inputs.conda_file == ''}}
        run: |
          az ml environment create --file ${{ github.workspace }}/${{ inputs.environment_file }} --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }}
      - name: create-environment-from-image
        if: ${{ inputs.dockerfile-location != ''}}
        run: |
          az ml environment create --file ${{ github.workspace }}/${{ inputs.environment_file }} --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }} --build-context ${{ github.workspace }}/${{ inputs.dockerfile-location }}
