name: taxi-deploy-batch-endpoint-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
      uses: aradman/mlops-v2/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-dev.yml
  create-compute:
      needs: get-config
      uses: aradman/mlops-v2/.github/workflows/create-compute.yml@main
      with:
        cluster_name: taxi-batch-cluster
        size: STANDARD_DS3_V2
        min_instances: 0
        max_instances: 5
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
        dply_environment: ${{ needs.get-config.outputs.environment }}    
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
  delete-endpoint:
      needs: [get-config,create-compute]
      uses: aradman/mlops-v2/.github/workflows/create-endpoint.yml@main
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: usecase/taxi/mlops/azureml/deploy/batch/batch-endpoint.yml
        endpoint_name:  ${{ format('taxi-gha-{0}', needs.get-config.outputs.bep) }} 
        endpoint_type: batch
        dply_environment: ${{ needs.get-config.outputs.environment }} 
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
  create-deployment:
      uses: aradman/mlops-v2/.github/workflows/create-deployment.yml@main
      needs: [get-config,create-endpoint]
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
        endpoint_file: usecase/taxi/mlops/azureml/deploy/batch/batch-deployment.yml
        endpoint_name: ${{ format('taxi-gha-{0}', needs.get-config.outputs.bep) }} 
        endpoint_type: batch
        deployment_name: eptestdeploy
        dply_environment: ${{ needs.get-config.outputs.environment }} 
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
